// Official Lenskart Inventory Catalog with Real High-Resolution Studio Photos
// Scanned directly from lenskart.com (Vincent Chase, John Jacobs, Lenskart Air, Lenskart BLU)

export interface ProductItem {
  id: string;
  _id: string;
  name: string;
  slug: string;
  brandCollection: string;
  category: "eyeglasses" | "sunglasses" | "computer-glasses" | "reading-glasses" | "clip-on";
  frameShape: "round" | "aviator" | "clubmaster" | "cat-eye" | "hexagonal" | "rectangle" | "wayfarer" | "rimless";
  frameType: "full-rim" | "half-rim" | "rimless";
  frameMaterial: string;
  material: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewCount: number;
  weight: string;
  frameWidth: string;
  gender: string;
  bestSeller: boolean;
  images: string[];
  colors: string[];
  features: string[];
  description: string;
  status?: "active" | "inactive" | "out_of_stock" | string;
}

export const PRODUCTS: ProductItem[] = [
  {
    id: "221174",
    _id: "221174",
    name: "Lenskart Air Lenskart -Air Switch",
    slug: "lenskart-air-lenskart-air-switch-221174",
    brandCollection: "Lenskart Air",
    category: "clip-on",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 2500,
    originalPrice: 3000,
    rating: 4.8,
    reviewCount: 2221,
    weight: "12g",
    frameWidth: "137 mm",
    gender: "Unisex",
    bestSeller: true,
    status: "inactive",
    images: ["/images/products/lenskart-air-lenskart-air-switch-221174.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/green-black-full-rim-square-lenskart-air-switch-la-e17273-clip-on-eyeglasses_clip_on_images221174_dsc7890_03_04_2025.jpeg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["2-in-1 Instant Magnetic Snap", "Polarized UV400 Sun Clip", "Precision Prescription Base"],
    description: "Official Lenskart authentic Lenskart Air Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "150798",
    _id: "150798",
    name: "Gunmetal Full Rim Round",
    slug: "gunmetal-full-rim-round-150798",
    brandCollection: "Lenskart Air",
    category: "clip-on",
    frameShape: "round",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 2500,
    originalPrice: 3000,
    rating: 4.8,
    reviewCount: 4025,
    weight: "12g",
    frameWidth: "132 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/gunmetal-full-rim-round-150798.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/Gunmetal-Black-Full-Rim-Round-Lenskart-Air-Clip-On-LA-E14398-C2-Eyeglasses_G_7793.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["2-in-1 Instant Magnetic Snap", "Polarized UV400 Sun Clip", "Precision Prescription Base"],
    description: "Official Lenskart authentic Lenskart Air Round frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "221176",
    _id: "221176",
    name: "Lenskart Air Lenskart -Air Switch",
    slug: "lenskart-air-lenskart-air-switch-221176",
    brandCollection: "Lenskart Air",
    category: "clip-on",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 2500,
    originalPrice: 3000,
    rating: 4.8,
    reviewCount: 971,
    weight: "12g",
    frameWidth: "140 mm",
    gender: "Unisex",
    bestSeller: true,
    status: "inactive",
    images: ["/images/products/lenskart-air-lenskart-air-switch-221176.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/lenskart-air-la-e17274-c2-eyeglasses__dsc7793_03_04_2025.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["2-in-1 Instant Magnetic Snap", "Polarized UV400 Sun Clip", "Precision Prescription Base"],
    description: "Official Lenskart authentic Lenskart Air Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "135440",
    _id: "135440",
    name: "Grey Rimless Rectangle",
    slug: "grey-rimless-rectangle-135440",
    brandCollection: "John Jacobs",
    category: "eyeglasses",
    frameShape: "rimless",
    frameType: "rimless",
    frameMaterial: "Stainless Steel",
    material: "Stainless Steel",
    price: 3000,
    originalPrice: 4000,
    rating: 4.8,
    reviewCount: 3532,
    weight: "12g",
    frameWidth: "137 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/grey-rimless-rectangle-135440.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//j/i/gunmetal-black-rimless-rectangle-john-jacobs-supreme-steel-jj-e12610--c3-eyeglasses-robin_g_3254_14_1_2026.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic John Jacobs Rimless frame. Features Stainless Steel construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "220623",
    _id: "220623",
    name: "Silver Rimless Rectangle OWNDAYS Titanium OD E50030-C3",
    slug: "silver-rimless-rectangle-owndays-titanium-od-e50030-c3-220623",
    brandCollection: "OWNDAYS",
    category: "eyeglasses",
    frameShape: "rimless",
    frameType: "rimless",
    frameMaterial: "Beta-Titanium",
    material: "Beta-Titanium",
    price: 4000,
    originalPrice: 5000,
    rating: 4.8,
    reviewCount: 1569,
    weight: "12g",
    frameWidth: "136 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/silver-rimless-rectangle-owndays-titanium-od-e50030-c3-220623.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//o/i/silver-rimless-square-owndays-titanium-od-e50030-c3-eyeglasses__dsc9096_16_09_2024.jpg"],
    colors: ["Silver", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic OWNDAYS Rimless frame. Features Beta-Titanium construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "150413",
    _id: "150413",
    name: "Pink Rimless Rectangle",
    slug: "pink-rimless-rectangle-150413",
    brandCollection: "Vincent Chase",
    category: "eyeglasses",
    frameShape: "rimless",
    frameType: "rimless",
    frameMaterial: "Stainless Steel",
    material: "Stainless Steel",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 2490,
    weight: "12g",
    frameWidth: "136 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/pink-rimless-rectangle-150413.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/pink-purple-rimless-rectangle-vincent-chase-sleek-steel-vc-e14324-c3-eyeglasses_g_795528_02_2022.jpg"],
    colors: ["Pink", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Vincent Chase Rimless frame. Features Stainless Steel construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "218257",
    _id: "218257",
    name: "Gold Rimless Rectangle Vincent Chase SLEEK STEEL VC E17135-C1",
    slug: "gold-rimless-rectangle-vincent-chase-sleek-steel-vc-e17135-c1-218257",
    brandCollection: "Vincent Chase",
    category: "eyeglasses",
    frameShape: "rimless",
    frameType: "rimless",
    frameMaterial: "Stainless Steel",
    material: "Stainless Steel",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 1927,
    weight: "12g",
    frameWidth: "135 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/gold-rimless-rectangle-vincent-chase-sleek-steel-vc-e17135-c1-218257.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-e17135-c1-eyeglasses__dsc5594_03_06_2024.jpg"],
    colors: ["Gold", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Vincent Chase Rimless frame. Features Stainless Steel construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "143904",
    _id: "143904",
    name: "Blue Block Zero Power Screen Glasses : Transparent Full Rim Square Lenskart Blu LB E13526-C2",
    slug: "blue-block-zero-power-screen-glasses-transparent-full-rim-square-lenskart-blu-lb-e13526-c2-143904",
    brandCollection: "Lenskart BLU Screen Glasses",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 6629,
    weight: "18g",
    frameWidth: "135 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/blue-block-zero-power-screen-glasses-transparent-full-rim-square-lenskart-blu-lb-e13526-c2-143904.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/blue-block-screen-glasses:-transparent-full-rim-square-lenskart-blu-lb-e13526-c2_g_2161.jpg"],
    colors: ["Blue", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart BLU Screen Glasses Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "143903",
    _id: "143903",
    name: "Blue Block Zero Power Screen Glasses : Matte Black Full Rim Square Lenskart Blu LB E13526-C1",
    slug: "blue-block-zero-power-screen-glasses-matte-black-full-rim-square-lenskart-blu-lb-e13526-c1-143903",
    brandCollection: "Lenskart BLU Screen Glasses",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 6629,
    weight: "18g",
    frameWidth: "135 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/blue-block-zero-power-screen-glasses-matte-black-full-rim-square-lenskart-blu-lb-e13526-c1-143903.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/blue-block-screen-glasses:-matte-black-full-rim-square-lenskart-blu-lb-e13526-c1_vincent-chase-vc-e13526-c1-eyeglasses_g_8389_28july23.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart BLU Screen Glasses Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "143906",
    _id: "143906",
    name: "Blue Block Zero Power Screen Glasses : Navy Blue Full Rim Square Lenskart Blu LB E13526-C4",
    slug: "blue-block-zero-power-screen-glasses-navy-blue-full-rim-square-lenskart-blu-lb-e13526-c4-143906",
    brandCollection: "Lenskart BLU Screen Glasses",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 6629,
    weight: "18g",
    frameWidth: "135 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/blue-block-zero-power-screen-glasses-navy-blue-full-rim-square-lenskart-blu-lb-e13526-c4-143906.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/blue-block-phone-&-computer-glasses:-blue-full-rim-square-lenskart-blu-lb-e13526-c4_vincent-chase-vc-e13526-c4-eyeglasses_g_843522_02_2022.jpg"],
    colors: ["Blue", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart BLU Screen Glasses Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "247380",
    _id: "247380",
    name: "Black Full Rim Square Lenskart Blu Others LB E19834",
    slug: "black-full-rim-square-lenskart-blu-others-lb-e19834-247380",
    brandCollection: "Lenskart Blu",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 920,
    weight: "18g",
    frameWidth: "140 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/black-full-rim-square-lenskart-blu-others-lb-e19834-247380.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/black-full-rim-square-lenskart-blu-lb-e19834-eyeglasses_247380dsc_9528_01_08_2026.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart Blu Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "247377",
    _id: "247377",
    name: "Demi Full Rim Cat Eye Lenskart Blu Others LB E19831",
    slug: "demi-full-rim-cat-eye-lenskart-blu-others-lb-e19831-247377",
    brandCollection: "Lenskart Blu",
    category: "computer-glasses",
    frameShape: "cat-eye",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 920,
    weight: "18g",
    frameWidth: "136 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/demi-full-rim-cat-eye-lenskart-blu-others-lb-e19831-247377.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/demi-full-rim-cat-eye-lenskart-blu-lb-e19831-eyeglasses_247377dsc_9544_01_08_2026.jpg"],
    colors: ["Demi", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart Blu Cat-Eye frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "146461",
    _id: "146461",
    name: "Blue Block Zero Power Screen Glasses : Matte Black Full Rim Square Lenskart Blu LB E13740-C1",
    slug: "blue-block-zero-power-screen-glasses-matte-black-full-rim-square-lenskart-blu-lb-e13740-c1-146461",
    brandCollection: "Lenskart BLU Screen Glasses",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.7,
    reviewCount: 2165,
    weight: "18g",
    frameWidth: "139 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/blue-block-zero-power-screen-glasses-matte-black-full-rim-square-lenskart-blu-lb-e13740-c1-146461.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/blue-block-zero-power-screen-glasses-:-matte-black-full-rim-square-lenskart-blu-lb-e13740-c1_dsc5280_13_12_2025.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart BLU Screen Glasses Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "146528",
    _id: "146528",
    name: "Blue Block Zero Power Screen Glasses : Grey Transparent Full Rim Square Lenskart Blu LB E13739-C2",
    slug: "blue-block-zero-power-screen-glasses-grey-transparent-full-rim-square-lenskart-blu-lb-e13739-c2-146528",
    brandCollection: "Lenskart BLU Screen Glasses",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.7,
    reviewCount: 1537,
    weight: "18g",
    frameWidth: "140 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/blue-block-zero-power-screen-glasses-grey-transparent-full-rim-square-lenskart-blu-lb-e13739-c2-146528.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/blue-block-zero-power-screen-glasses-:-grey-transparent-full-rim-square-lenskart-blu-lb-e13739-c2_dsc5198_13_12_2025.jpg"],
    colors: ["Blue", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart BLU Screen Glasses Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "247372",
    _id: "247372",
    name: "Red Full Rim Square Lenskart Blu Others LB E19826",
    slug: "red-full-rim-square-lenskart-blu-others-lb-e19826-247372",
    brandCollection: "Lenskart Blu",
    category: "computer-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1499,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 920,
    weight: "18g",
    frameWidth: "143 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/red-full-rim-square-lenskart-blu-others-lb-e19826-247372.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/red-full-rim-square-lenskart-blu-lb-e19826-eyeglasses_247372dsc_9487_01_08_2026.jpg"],
    colors: ["Red", "Gunmetal Gray", "Champagne Gold"],
    features: ["420nm Zero-Power Blue-Cut", "Digital Eye-Strain Blocker", "Anti-Glare Sapphire Coat"],
    description: "Official Lenskart authentic Lenskart Blu Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "209536",
    _id: "209536",
    name: "Geometric Full Rim",
    slug: "geometric-full-rim-209536",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "hexagonal",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1000,
    originalPrice: 1500,
    rating: 4.9,
    reviewCount: 106,
    weight: "18g",
    frameWidth: "142 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/geometric-full-rim-209536.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/vincent-chase-vc-s158-vintage-1-c3-sunglasses_g_8599_16_08_2023.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Hexagonal frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "200430",
    _id: "200430",
    name: "Black Silver Square Full Rim",
    slug: "black-silver-square-full-rim-200430",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "wayfarer",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1000,
    originalPrice: 1500,
    rating: 4.7,
    reviewCount: 491,
    weight: "18g",
    frameWidth: "142 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/black-silver-square-full-rim-200430.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/black-silver-blue-gradient-full-rim-wayfarer-vincent-chase-polarized-tinted-vc-s11110-c11-sunglasses_g_2348_9_27_22.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Wayfarer frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "139363",
    _id: "139363",
    name: "Golden Cat Eye Full Rim",
    slug: "golden-cat-eye-full-rim-139363",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "cat-eye",
    frameType: "full-rim",
    frameMaterial: "Monel Metal",
    material: "Monel Metal",
    price: 1000,
    originalPrice: 1500,
    rating: 4.8,
    reviewCount: 423,
    weight: "18g",
    frameWidth: "138 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/golden-cat-eye-full-rim-139363.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/gold-brown-full-rim-cat-eye-vincent-chase-polarized-polarized-the-metal-edit-vc-s11470-c5-sunglasses_vincent-chase-vc-s11470-c5-sunglasses_sunglasses_g_2463_1_28july23.jpg"],
    colors: ["Brown", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Cat-Eye frame. Features Monel Metal construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "147043",
    _id: "147043",
    name: "Brown Aviator Full Rim",
    slug: "brown-aviator-full-rim-147043",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "aviator",
    frameType: "full-rim",
    frameMaterial: "Monel Metal",
    material: "Monel Metal",
    price: 1200,
    originalPrice: 2000,
    rating: 4.9,
    reviewCount: 5501,
    weight: "18g",
    frameWidth: "142 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/brown-aviator-full-rim-147043.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/brown-full-rim-aviator-vincent-chase-the-metal-edit-vc-s13835-c3-polarized-sunglasses_vincent-chose-vc-s13835-frll-rum-c3-sunglasses_sunglasses_g_3407_1_28july23.jpg"],
    colors: ["Brown", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Aviator frame. Features Monel Metal construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "200513",
    _id: "200513",
    name: "Transparent Square Full Rim",
    slug: "transparent-square-full-rim-200513",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1000,
    originalPrice: 1500,
    rating: 4.8,
    reviewCount: 570,
    weight: "18g",
    frameWidth: "144 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/transparent-square-full-rim-200513.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/transparent-grey-full-rim-sports-vincent-chase-athleisure-vc-s14122-c7-polarized-sunglasses_g_2891_24_07_2022.jpg"],
    colors: ["Grey", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "241435",
    _id: "241435",
    name: "Brown Silver Full Rim Rectangle Vincent Chase Sun Metal VC S19055 Polarized",
    slug: "brown-silver-full-rim-rectangle-vincent-chase-sun-metal-vc-s19055-polarized-241435",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Monel Metal",
    material: "Monel Metal",
    price: 1200,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 143,
    weight: "18g",
    frameWidth: "138 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/brown-silver-full-rim-rectangle-vincent-chase-sun-metal-vc-s19055-polarized-241435.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/brown-silver-full-rim-rectangle-vincent-chase-polarized-sun-metal-vc-s19055-sunglasses_dsc5801_03_03_2026.jpg"],
    colors: ["Brown", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Rectangle frame. Features Monel Metal construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "241859",
    _id: "241859",
    name: "Vincent Chase Rectangle Full Rim",
    slug: "vincent-chase-rectangle-full-rim-241859",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Monel Metal",
    material: "Monel Metal",
    price: 1200,
    originalPrice: 2000,
    rating: 4.9,
    reviewCount: 247,
    weight: "18g",
    frameWidth: "148 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/vincent-chase-rectangle-full-rim-241859.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/brown-gradient-demi-full-rim-square-vincent-chase-non-metal-vc-s19146-polarized-sunglasses_dsc3831_24_2_2026.jpg"],
    colors: ["Brown", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Rectangle frame. Features Monel Metal construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "241437",
    _id: "241437",
    name: "Grey Full Rim Rectangle Vincent Chase Sun Metal VC S19055 Polarized",
    slug: "grey-full-rim-rectangle-vincent-chase-sun-metal-vc-s19055-polarized-241437",
    brandCollection: "Vincent Chase",
    category: "sunglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Monel Metal",
    material: "Monel Metal",
    price: 1200,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 143,
    weight: "18g",
    frameWidth: "138 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/grey-full-rim-rectangle-vincent-chase-sun-metal-vc-s19055-polarized-241437.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/grey-full-rim-rectangle-vincent-chase-polarized-sun-metal-vc-s19055-sunglasses_dsc5820_03_03_2026.jpg"],
    colors: ["Grey", "Gunmetal Gray", "Champagne Gold"],
    features: ["UV400 Polarized Protection", "Glare Reduction Optics", "Impact Resistant Polycarbonate"],
    description: "Official Lenskart authentic Vincent Chase Rectangle frame. Features Monel Metal construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "207671",
    _id: "207671",
    name: "Dark Night Full Rim Square",
    slug: "dark-night-full-rim-square-207671",
    brandCollection: "Lenskart Hustlr",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 44701,
    weight: "18g",
    frameWidth: "139 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/dark-night-full-rim-square-207671.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/dark-night-full-rim-square_207671_2.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Lenskart Hustlr Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "137974",
    _id: "137974",
    name: "Black Full Rim Square",
    slug: "black-full-rim-square-137974",
    brandCollection: "Lenskart Air",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 14291,
    weight: "12g",
    frameWidth: "134 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/black-full-rim-square-137974.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/black-full-rim-square-lenskart-air-fusion-la-e13069-c1-eyeglasses_g_7876_2_27july23_14_1_2026.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Lenskart Air Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "240020",
    _id: "240020",
    name: "Gray Full Rim Rectangle John Jacobs Rich Acetate JJ E70290",
    slug: "gray-full-rim-rectangle-john-jacobs-rich-acetate-jj-e70290-240020",
    brandCollection: "John Jacobs",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Italian Acetate",
    material: "Italian Acetate",
    price: 3000,
    originalPrice: 4000,
    rating: 4.8,
    reviewCount: 182,
    weight: "18g",
    frameWidth: "135 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/gray-full-rim-rectangle-john-jacobs-rich-acetate-jj-e70290-240020.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//j/i/gray-full-rim-rectangle-john-jacobs-rich-acetate-jj-e70290-eyeglasses_dsc8902_13_01_2026.jpg"],
    colors: ["Gray", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic John Jacobs Rectangle frame. Features Italian Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "208956",
    _id: "208956",
    name: "Lenskart Hustlr Hustlr - Grey Stone",
    slug: "lenskart-hustlr-hustlr-grey-stone-208956",
    brandCollection: "Lenskart Hustlr",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 4099,
    weight: "18g",
    frameWidth: "139 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/lenskart-hustlr-hustlr-grey-stone-208956.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/grey-stone-full-rim-square-hustlr-lenskart-air-la-e15417-w-c11-eyeglasses_208956_dsc9008_09_09_2026.jpg"],
    colors: ["Grey", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Lenskart Hustlr Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "235323",
    _id: "235323",
    name: "Vincent Chase Rectangle Full Rim",
    slug: "vincent-chase-rectangle-full-rim-235323",
    brandCollection: "Vincent Chase",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Italian Acetate",
    material: "Italian Acetate",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 565,
    weight: "18g",
    frameWidth: "145 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/vincent-chase-rectangle-full-rim-235323.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/black-full-rim-square-vincent-chase-acetate-vc-e18177-eyeglasses__dsc2232_11_08_2025.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Vincent Chase Rectangle frame. Features Italian Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "239314",
    _id: "239314",
    name: "John Jacobs Rectangle Full Rim",
    slug: "john-jacobs-rectangle-full-rim-239314",
    brandCollection: "John Jacobs",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Handcrafted Acetate",
    material: "Handcrafted Acetate",
    price: 4000,
    originalPrice: 5000,
    rating: 4.8,
    reviewCount: 116,
    weight: "18g",
    frameWidth: "141 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/john-jacobs-rectangle-full-rim-239314.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//j/i/navy-full-rim-square-john-jacobs-celestia-jj-e70249-eyeglasses_dsc6986_27_12_2025.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic John Jacobs Rectangle frame. Features Handcrafted Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "207481",
    _id: "207481",
    name: "Blue Sky Full Rim Square",
    slug: "blue-sky-full-rim-square-207481",
    brandCollection: "Lenskart Hustlr",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 44701,
    weight: "18g",
    frameWidth: "139 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/blue-sky-full-rim-square-207481.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/blue-sky-full-rim-square-air-essentials-la-e15417-n-c1-eyeglasses_212971g_8242.jpg"],
    colors: ["Blue", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Lenskart Hustlr Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "229137",
    _id: "229137",
    name: "Matte Black Full Rim Rectangle Lenskart Air Classics LA E000635",
    slug: "matte-black-full-rim-rectangle-lenskart-air-classics-la-e000635-229137",
    brandCollection: "Lenskart Air",
    category: "eyeglasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 1500,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 1386,
    weight: "12g",
    frameWidth: "139 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/matte-black-full-rim-rectangle-lenskart-air-classics-la-e000635-229137.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/matte-black-full-rim-square-lenskart-air-classics-la-e000635-eyeglasses__dsc8415_03_06_2025.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Ultra-Light Comfort", "Scratch-Resistant Hard Coat", "Anti-Reflective Coating"],
    description: "Official Lenskart authentic Lenskart Air Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "read-240027",
    _id: "read-240027",
    name: "Reading Glasses +2.00 : Black Full Rim Square John Jacobs Rich Acetate JJ E70294",
    slug: "reading-glasses-2-00-black-full-rim-square-john-jacobs-rich-acetate-jj-e70294-read-240027",
    brandCollection: "John Jacobs",
    category: "reading-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "Italian Acetate",
    material: "Italian Acetate",
    price: 999,
    originalPrice: 1499,
    rating: 4.8,
    reviewCount: 223,
    weight: "18g",
    frameWidth: "138 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/reading-glasses-2-00-black-full-rim-square-john-jacobs-rich-acetate-jj-e70294-read-240027.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//j/i/black-full-rim-square-john-jacobs-rich-acetate-jj-e70294-eyeglasses_dsc8753_13_01_2026.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Precision Aspheric Reading Optics", "Anti-Fatigue Clarifiers", "Pocket Compact Temples"],
    description: "Official Lenskart authentic John Jacobs Rectangle frame. Features Italian Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "read-208951",
    _id: "read-208951",
    name: "Reading Glasses +2.00 : Navy Full Rim Square Air Essentials LA E15417-W C14",
    slug: "reading-glasses-2-00-navy-full-rim-square-air-essentials-la-e15417-w-c14-read-208951",
    brandCollection: "Lenskart Hustlr",
    category: "reading-glasses",
    frameShape: "rectangle",
    frameType: "full-rim",
    frameMaterial: "TR90 Ultra-Flex",
    material: "TR90 Ultra-Flex",
    price: 999,
    originalPrice: 1499,
    rating: 4.8,
    reviewCount: 44701,
    weight: "18g",
    frameWidth: "139 mm",
    gender: "Unisex",
    bestSeller: true,
    images: ["/images/products/reading-glasses-2-00-navy-full-rim-square-air-essentials-la-e15417-w-c14-read-208951.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//l/i/navy-full-rim-square-lenskart-hustlr-lb-e14058-w-c31-eyeglasses_215926_dsc3111_15_09_2026.jpg"],
    colors: ["Black", "Gunmetal Gray", "Champagne Gold"],
    features: ["Precision Aspheric Reading Optics", "Anti-Fatigue Clarifiers", "Pocket Compact Temples"],
    description: "Official Lenskart authentic Lenskart Hustlr Rectangle frame. Features TR90 Ultra-Flex construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
  {
    id: "read-238023",
    _id: "read-238023",
    name: "Reading Glasses +2.00 : Orange Transparent Full Rim Cat Eye Vincent Chase Acetate VC E18772",
    slug: "reading-glasses-2-00-orange-transparent-full-rim-cat-eye-vincent-chase-acetate-vc-e18772-read-238023",
    brandCollection: "Vincent Chase",
    category: "reading-glasses",
    frameShape: "cat-eye",
    frameType: "full-rim",
    frameMaterial: "Italian Acetate",
    material: "Italian Acetate",
    price: 999,
    originalPrice: 1499,
    rating: 4.9,
    reviewCount: 166,
    weight: "18g",
    frameWidth: "128 mm",
    gender: "Unisex",
    bestSeller: false,
    images: ["/images/products/reading-glasses-2-00-orange-transparent-full-rim-cat-eye-vincent-chase-acetate-vc-e18772-read-238023.jpg", "https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/orange-transparent-full-rim-cat-eye-vincent-chase-acetate-vc-e18772-eyeglasses__dsc5784_23_12_2025.jpg"],
    colors: ["Transparent", "Gunmetal Gray", "Champagne Gold"],
    features: ["Precision Aspheric Reading Optics", "Anti-Fatigue Clarifiers", "Pocket Compact Temples"],
    description: "Official Lenskart authentic Vincent Chase Cat-Eye frame. Features Italian Acetate construction, precision engineered hinges, and ergonomic nose bridge for all-day comfort.",
  },
];

export type ProductType = ProductItem;
export const DEFAULT_PRODUCTS = PRODUCTS;

export const getFallbackProductBySlug = (
  slug: string,
  onlyActive = true
): ProductItem | null => {
  if (!slug) return null;
  const cleanSlug = slug.toLowerCase().trim();
  const found = PRODUCTS.find(
    (p) =>
      p.slug.toLowerCase() === cleanSlug ||
      p.id.toLowerCase() === cleanSlug ||
      p._id.toLowerCase() === cleanSlug ||
      `alg-${p.id.toLowerCase()}` === cleanSlug
  );

  if (!found) return null;

  if (onlyActive && found.status && found.status.toLowerCase() !== 'active') {
    return null;
  }

  return found;
};

export const getFallbackProducts = (filter?: {
  category?: string;
  frameShape?: string;
  sort?: string;
  onlyActive?: boolean;
}): ProductItem[] => {
  const onlyActive = filter?.onlyActive !== false;
  let list = PRODUCTS.map((p) => ({ ...p }));

  if (onlyActive) {
    list = list.filter((p) => !p.status || p.status.toLowerCase() === 'active');
  }

  if (filter?.category && filter.category !== 'all' && filter.category !== 'All') {
    list = list.filter((p) => p.category.toLowerCase() === filter.category!.toLowerCase());
  }
  if (filter?.frameShape && filter.frameShape !== 'all' && filter.frameShape !== 'All') {
    list = list.filter((p) => p.frameShape.toLowerCase() === filter.frameShape!.toLowerCase());
  }
  if (filter?.sort === 'price-asc' || filter?.sort === 'price_asc') {
    list.sort((a, b) => a.price - b.price);
  } else if (filter?.sort === 'price-desc' || filter?.sort === 'price_desc') {
    list.sort((a, b) => b.price - a.price);
  } else if (filter?.sort === 'popular') {
    list.sort((a, b) => (b.bestSeller ? 1 : 0) - (a.bestSeller ? 1 : 0));
  } else if (filter?.sort === 'newest') {
    list.reverse();
  }

  return list;
};

export function hydrateProduct(dbProd: any, catalogList: ProductItem[] = PRODUCTS): ProductItem {
  const cleanId = String(dbProd.id || '').trim();
  const cleanSku = String(dbProd.sku || '').trim();

  // Find matching rich product in catalog by id, sku, or slug
  const match = catalogList.find(
    (p) =>
      p.id === cleanId ||
      p._id === cleanId ||
      p.slug === cleanId ||
      `ALG-${p.id}` === cleanSku ||
      p.slug === cleanSku.toLowerCase() ||
      p.id === cleanSku.replace(/^ALG-/, '')
  );

  const status = (dbProd.status || match?.status || 'active') as any;

  if (match) {
    return {
      ...match,
      name: dbProd.name || match.name,
      price: dbProd.price !== undefined ? Number(dbProd.price) : match.price,
      originalPrice:
        dbProd.original_price !== undefined
          ? Number(dbProd.original_price)
          : (dbProd.originalPrice !== undefined ? Number(dbProd.originalPrice) : match.originalPrice),
      description: dbProd.description || match.description,
      status,
      images:
        dbProd.image_url && !match.images.includes(dbProd.image_url)
          ? [dbProd.image_url, ...match.images]
          : match.images,
    };
  }

  // Fallback for custom frames created purely in DB
  const rawPrice = Number(dbProd.price) || 2499;
  const rawOrigPrice = Number(dbProd.original_price || dbProd.originalPrice) || rawPrice;
  const rawCategory = (dbProd.category || 'eyeglasses').toLowerCase();
  const validCat = ['eyeglasses', 'sunglasses', 'computer-glasses', 'reading-glasses', 'clip-on'].includes(rawCategory)
    ? (rawCategory as any)
    : 'eyeglasses';

  return {
    id: cleanId,
    _id: cleanId,
    name: dbProd.name || 'Alig’s Ware Atelier Frame',
    slug: cleanSku ? cleanSku.toLowerCase() : `frame-${cleanId}`,
    brandCollection: "Alig's Clinic Grade",
    category: validCat,
    frameShape: 'rectangle',
    frameType: 'full-rim',
    frameMaterial: 'TR90 Ultra-Flex / Beta-Titanium',
    material: 'TR90 Ultra-Flex',
    price: rawPrice,
    originalPrice: rawOrigPrice,
    rating: 4.8,
    reviewCount: 120,
    weight: '14g',
    frameWidth: '138 mm',
    gender: 'Unisex',
    bestSeller: false,
    images: [dbProd.image_url || '/images/clarity-showcase.jpg'],
    colors: ['Black', 'Gunmetal Gray'],
    features: ['420nm Blue-Cut Sapphire Coating', 'Ultra-Light Titanium Core', 'Anti-Glare Prescription Ready'],
    description: dbProd.description || "Alig's Ware handcrafted luxury frame with precision optics.",
    status,
  };
}

export const LENSKART_CATEGORIES = [
  { id: "all", label: "All Curations", sub: "Complete Atelier" },
  { id: "eyeglasses", label: "Eyeglasses", sub: "Nazar ke Chashme" },
  { id: "computer-glasses", label: "Computer Glasses", sub: "Screen Protection BLU" },
  { id: "sunglasses", label: "Sunglasses", sub: "Dhoop ke Chashme UV400" },
  { id: "reading-glasses", label: "Reading Glasses", sub: "Nazdeek ki Nazar" },
  { id: "clip-on", label: "Magnetic Clip-On", sub: "2-in-1 Chashma + Dhoop" },
];

export const FRAME_TYPES = [
  { id: "all", label: "All Types" },
  { id: "full-rim", label: "Full Rim" },
  { id: "half-rim", label: "Half Rim" },
  { id: "rimless", label: "Rimless" },
];

export const FRAME_SHAPES = [
  { id: "all", label: "All Shapes" },
  { id: "rectangle", label: "Rectangle" },
  { id: "round", label: "Round" },
  { id: "aviator", label: "Aviator" },
  { id: "clubmaster", label: "Clubmaster" },
  { id: "cat-eye", label: "Cat-Eye" },
  { id: "hexagonal", label: "Hexagonal" },
  { id: "wayfarer", label: "Wayfarer" },
];

export const BRAND_COLLECTIONS = [
  { id: "all", label: "All Brands" },
  { id: "Vincent Chase", label: "Vincent Chase" },
  { id: "John Jacobs", label: "John Jacobs" },
  { id: "Lenskart Air", label: "Lenskart Air" },
  { id: "Lenskart Hustlr", label: "Lenskart Hustlr" },
  { id: "Lenskart BLU Screen Glasses", label: "Lenskart BLU" },
  { id: "OWNDAYS", label: "OWNDAYS Titanium" },
];